name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # Lintと単体テスト
      - run: pip install ruff pytest
      - run: pip install -r backend/requirements.txt
      - run: ruff check .
      - run: pytest -q

      #   docker内でテスト
      - uses: docker/setup-buildx-action@v3
      - run: docker build --target runtime -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
